
services:
  my_application:
    build: .
    volumes:
      - .:/var/www/html
      #- vendor_data:/var/www/html/vendor
      #- node_modules_data:/var/www/html/node_modules
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=alexis
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_datos:/var/lib/postgresql/data
    #ports:
      #- "4321:5432"


  web_server:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      #- .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my_application

volumes:
  postgres_datos:
  #vendor_data:
  #node_modules_data:

